### PR TITLE
Segregate_Past_Organisers

### PR DESCRIPTION
**Pull request by Rockyoudead8**
I Have Created a web page which deals with segregating the current and past oragnisers of contrihub .

## Description

As asked by the maintainer i have done every change possible and tried to make it interactive as much as possible 
I HAVE DONE THE FOLLOWING CHANGES --->

1.I have used HTML , CSS AND JAVASCRIPT AS MUCH AS I KNOW AND BEING FRANK I HAVE ALSO TOOK HELP OF AI TO DO SOME CSS WORK ONLY TO LOOK IT MORE ENGAGING ,

2. I HAVE A SECTION IN WHICH THE CURRENT ORGANISERS ARE SET TO DEFAULT WHICH MEANS THEY WILL BE VISIBLE ALWAYS AND AFTER THIS IN THE OTHER SECTIONS I HAVE CREATED A KIND OF DROP DOWN LIST WHICH OPENS ON CLICKING  AND SHOW OUR PAST ORGANISERS (23-24 AND 22-23).

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Related Issue

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [ x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [ x] My code follows the code style of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Review by meisabhishekpatel — COMMENTED** [review]
what the hell is this ?? I wanted you modify in the orginal page not just straight away copy and paste the code from sac.mnnit.ac.in/team, I just sent you that as a reference.

**Comment by Rockyoudead8** [comment]
I am really sorry sir would it be okay if i add more members and segregate
them as well on based of gender as well ?

**Comment by meisabhishekpatel** [comment]
@Rockyoudead8 i want you to modify the existing code

**Comment by meisabhishekpatel** [comment]
@Rockyoudead8 i am closing this PR since it's totally wrong

**Pull request closed without merging**
