### PR TITLE
added filter issue by open or close status

### LINKED ISSUE #188: Filter Issues by Status for Easier Contribution
### **Filter Issues by Status for Easier Contribution**

To make the contribution process more efficient, it would be helpful if contributors could filter issues based on their current status (open or closed). This would allow contributors to focus on tasks that are still available and easily reference completed issues.

#### **Issue Filtering:**
- Add a feature to filter the existing issues on the website based on their status (e.g., "Open" or "Closed").
- The filter should allow users to view only issues of a specific status.
- Users should be able to toggle between open and closed issues for a better overview of available and completed tasks.

### **Benefits:**
- This feature will allow contributors to focus on open issues that they can work on, improving the overall efficiency of contributions.
- Viewing closed issues can help contributors understand how similar problems were solved in the past.
- It will reduce confusion for contributors by clearly distinguishing available tasks from completed ones.

### PR DESCRIPTION
**Pull request by hexwhiz**
## Description

Added a new dropdown submenu in the filter option to filter issues based on their open or close status using a new view `filter_by_status`. Also fixed alignment of the submenus in the filter dropdown.

## Related Issue

Fixes #188 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots (if appropriate):
https://github.com/user-attachments/assets/b6db6581-2d3a-4798-a479-f69900270cb8

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Review by meisabhishekpatel — DISMISSED** [review]

**Comment by meisabhishekpatel** [comment]
@hexwhiz automated testing fails...

**Comment by hexwhiz** [comment]
Didn't ran the flake8 test. I will commit again after the check.

**Comment by hexwhiz** [comment]
@meisabhishekpatel done making changes. Now the test should pass

**Comment by meisabhishekpatel** [comment]
closes #189

**Pull request merged**
