### PR TITLE
Feat: Added Card for level Wise issue solved

### PR DESCRIPTION
**Pull request by VishalMinj**
## Added:
- Issue card to display levels
- Issue card to display total problems solved
## Update:
- Updated the profile view to query all the levels
- Updated the main profile page in home

### CODE REVIEW

**Comment by meisabhishekpatel** [comment]
@VishalMinj  ill review this PR tomorrow get it assigned through contrihub website as well

**Comment by VishalMinj** [comment]
Is this issue assigned to someone else rn?

**Comment by meisabhishekpatel** [comment]
@VishalMinj no the issue isn't assigned to anybody else

**Comment by VishalMinj** [comment]
Why does it start working only after i complain 💀. Anyways I've sent the request

**Comment by VishalMinj** [comment]
@meisabhishekpatel If you decide to merge pr, then please also assign #168 afterwards. I've already made the assignment request.

**Review by meisabhishekpatel — APPROVED** [review]
seems correct

**Comment by meisabhishekpatel** [comment]
reopen #169 

hey @VishalMinj you did not add very-easy tag in this do that as well

**Comment by VishalMinj** [comment]
If you need i can add query for that too, might take me a while to figure out a ui so all four level don't look stacked up

**Comment by meisabhishekpatel** [comment]
@VishalMinj take your time, but do add very-easy

**Pull request merged**
