### PR TITLE
Segregated past organisers section by year

### PR DESCRIPTION
**Pull request by ShouryaMishra2006**
Added year toggle option

This PR fixes the issue where the CSS for year navigation links was not being applied. The styles have been applied using JavaScript to ensure proper styling on hover and click events. The links now have consistent colors, transitions, and click effects.
I tested the changes locally on Chrome and Firefox. All links are styled correctly, with hover and click effects working as expected.
I have tried my best within given time frame to implement the required feature.
Screenshot (126)
Screenshot (125)

### CODE REVIEW

**Comment by meisabhishekpatel** [comment]
@ShouryaMishra2006 I wanted it like this - sac.mnnit.ac.in/team

**Comment by ShouryaMishra2006** [comment]
I have improved the section by including toggle button options
Screenshot (132)
Screenshot (131)

**Review by meisabhishekpatel — APPROVED** [review]
seems fine

**Comment by meisabhishekpatel** [comment]
closes #165

**Comment by meisabhishekpatel** [comment]
closes #165

**Pull request merged**
