### PR TITLE
project page update dynamically with github api

### LINKED ISSUE #177: Fetch Project Details Dynamically from GitHub API
### Description:
Currently, the project information displayed on `/projects` is hardcoded in the HTML template. We want to dynamically fetch project information from the GitHub API to ensure the page stays updated with the latest information.

### Requirements:
1. **Environment Variables**: 
   - The project names will be provided via environment variables.
   - Example: `PROJECT_NAMES="project1,project2,project3"`

2. **Fetch Public Repositories**:
   - Use the GitHub API to fetch details of repositories from the ContriHUB organization.
   - Match the project names (from environment variables) with the names of the public repositories in ContriHUB.

3. **Pull Information**:
   - For each matching repository, retrieve the following details:
     1. **Project Name**.
     2. **Maintainer**: The username of the repo owner or collaborator.
     3. **About**: The description (about) section of the repository.

4. **Dynamic Rendering**:
   - Update the Django view to fetch the project data dynamically and pass it to the template.
   - Modify the HTML template to display this dynamically fetched data.

### Tasks:
- [ ] Read project names from environment variables.
- [ ] Use GitHub API to fetch details of matching repositories.
- [ ] Extract relevant information: name, maintainer, and about section.
- [ ] Update the `/projects` page to display fetched data dynamically.

### PR DESCRIPTION
**Pull request by hexwhiz**
## Description

Added more fields **(mentor, mentor url, description)** in project schema in database. So, whenever admin hit the populate_project endpoint, details of any new project in the env file will get fetched from github using github API and will be populated in the database. The project homepage now updates dynamically based on the projects names present in the environment variables. 

## Related Issue

Fixes #177 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

This change was necessary because on addition of new projects the project page was not updated automatically. 

## How Has This Been Tested?

I had to remove the admin status check from the populate_project view to hit the populate_project endpoint. But that change has been reversed in this PR. I had 4 projects in env file and then hit the endpoint which populated the data of projects in database. Then refreshing the project page shows the project details present in the database. **The moviescreen project have no description on github that's why it shows None.**

## Screenshots (if appropriate):
image
image

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

### CODE REVIEW

**Comment by meisabhishekpatel** [comment]
@hexwhiz why are you adding ENV variable like CONTRIHUB_MENTOR etc in this is there a specific need, then tell why ? Can you please do it without changing the ENV

**Comment by hexwhiz** [comment]
@meisabhishekpatel This variable is for the mentor of contrihub-24 repo. If env shouldn't be changed then I would just have to hardcode the mentor in the views.py file. Or I could keep the variables in settings.py and remove them from env.

**Comment by hexwhiz** [comment]
@meisabhishekpatel should I make the changes then?

**Comment by meisabhishekpatel** [comment]
@hexwhiz no changes I'll properly review the PR then tell you

**Comment by meisabhishekpatel** [comment]
@hexwhiz can you update the sample env for the changes you have done

**Comment by hexwhiz** [comment]
Okay i will

**Comment by meisabhishekpatel** [comment]
@hexwhiz doesn't seem to be working can you check.

**Comment by meisabhishekpatel** [comment]
@hexwhiz can you explain how are you update the projects on the page, like suppose I have few projects already in my env and i want to add let say 2 more projects , how will I add that

**Comment by hexwhiz** [comment]
Add projects to AVAILABLE_PROJECTS env variable. Then hit the /populate_project endpoint. This will load the project details in database. Then opening the project page will show the projects.

**Comment by hexwhiz** [comment]
For new projects just add there name in the env variable

**Comment by hexwhiz** [comment]
Done updating the sample env

**Comment by meisabhishekpatel** [comment]
@hexwhiz tell me will clicking on populate project endpoint will it update the description or mentor, if it's already present in the db or not, if not then please make it like populate issues end points like it updates all the active issues in the db.

**Comment by hexwhiz** [comment]
Oh! you are right. That populate_project view was set to skip the projects those were already present in database. I can just remove that check and it would then update all the projects in database when you hit populate_project. Would it be ok?

**Comment by hexwhiz** [comment]
@meisabhishekpatel do you want the projects to be updated when you hit `/populate_projects` or  `/populate_issues`?

**Comment by meisabhishekpatel** [comment]
i want to update all the pre - existing project such that let say I changed description of my repo in github it should be updated when I hit populate_project button, and add the projects which are not already present in the db



> do you want the projects to be updated when you hit `/populate_projects` or `/populate_issues`?

/populate_projects

**Comment by hexwhiz** [comment]
Ok I have that ready I will commit after a few minutes

**Comment by hexwhiz** [comment]
@meisabhishekpatel done making changes. One more thing, when I was testing the project, I hit the Github API limit. So I had to use API_TOKEN from github. I have updated the sample_env.txt for the same. Now this /populate_project endpoint updates the details of already added projects and remove any project that is in the database but not in the .env file.

**Comment by hexwhiz** [comment]
@meisabhishekpatel any update?

**Comment by meisabhishekpatel** [comment]
@hexwhiz can you just remove API_TOKEN thing you must have reached api limit due to numerous testing

**Comment by hexwhiz** [comment]
Ok i will remove that

**Comment by meisabhishekpatel** [comment]
@hexwhiz just make it like populate issues, see how populate issues is implemented.

**Comment by hexwhiz** [comment]
@meisabhishekpatel done making changes. Sorry for these many commits, the build test was failing a lot😥

**Comment by meisabhishekpatel** [comment]
@hexwhiz will review it soon

**Comment by hexwhiz** [comment]
@meisabhishekpatel would you please review this? ContriHUB is ending😅

**Comment by meisabhishekpatel** [comment]
@hexwhiz even if pending review will be happening even after contrihub ends and you will be awarded points

**Comment by meisabhishekpatel** [comment]
@hexwhiz I have some doubts about it so not merging this PR but it is indeed acceptable to I'll give you points and add a hacktoberfest-accepted label so that it gets counted in hacktoberfest

**Comment by hexwhiz** [comment]
Ok thanks. I am open for feedback if I did something wrong

**Pull request closed without merging**
